# Generated by Django 3.0.9 on 2020-09-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20200902_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
